version: '3.8'

services:
  postgres:
    image: postgres:14-alpine
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: webapp_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123456
    ports:
      - "5435:5432" # Container Post Listen  on 5432 , Map to Host 5435
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: